### ISSUE TITLE
本リポジトリのライセンス

### ISSUE THREAD

**Issue by yofukami** [icat-lab/seminar_design_hakuba#1]
[深見基礎ゼミ2021年度1学期同様](https://github.com/icat-lab/ay2021spring_icatlab/blob/main/LICENSE)、Creative Commons Attribution 4.0 Internationalでよいでしょうか？

**Comment by Gucchiy** [comment]
こちらも特に知財に絡むような記載は行わないため、問題ないと思います。

**Comment by yofukami** [comment]
[こちらの通り](https://github.com/icat-lab/seminar_design_hakuba/blob/main/LICENSE)ライセンスを設定しました。
