### ISSUE TITLE
Projectの立ち上げ手法規定

### ISSUE THREAD

**Issue by yofukami** [icat-lab/seminar_design_hakuba#12]
Basic Kanbanでよいでしょうか？

**Comment by Gucchiy** [comment]
@yofukami これは、学生達が Project を使うことを想定している、と言う理解であってますか？その場合は BASIC Kanban が一番簡単なので、良いとは思いますね

**Comment by yofukami** [comment]
@Gucchiy はい。 #7 でも触れていますが、issueを整理して、管理する機能としてのProjectは、平易に使える上に、project managementを学ぶ上で重要だと考えています。
使うとすると、Basic Kanbanということで確定で。

**Comment by Gucchiy** [comment]
@yofukami はい、ツールの設定としては、BASIC Kanban 以上はちょっと難しいということもあって、確定で了解です。
いつ・どののような意図で Project を作って、どのような意図で Issue を作成するか、またさらにそれが Pull Request にどうつながるのか？というあたりを全体で確認したいということで、 #4 で引き続き確認させてくださいませ。もし、本 issue が Project の設定だけが意図である場合はクローズで良いと思うのですが、タイトルとしてはその意図ではない？

**Comment by yofukami** [comment]
@Gucchiy はい。単にprojectを使わせるというよりは、プロジェクトマネジメントとしてのissues/project/codeを包括的に理解してほしいという意図です。一度ここはcloseして、 #4 で引き続き全体を検討するという形でいかがでしょうか？
