### ISSUE TITLE
コラボレーションスペースのライセンス

### ISSUE THREAD

**Issue by yofukami** [icat-lab/seminar_design_hakuba#2]
[コラボレーションスペース](https://github.com/icat-lab/ay2021autumn_Hakuba)も、[深見基礎ゼミ2021年度1学期同様](https://github.com/icat-lab/ay2021spring_icatlab/blob/main/LICENSE)、Creative Commons Attribution 4.0 Internationalでよいでしょうか？

**Comment by Gucchiy** [comment]
はい、良いと思います！特に知財に絡むことは記載しないと思います。

**Comment by yofukami** [comment]
[こちらの通り](https://github.com/icat-lab/ay2021autumn_Hakuba/blob/main/LICENSE)設定しました。
