### ISSUE TITLE
図書館ガイダンスをいつ入れるか

### ISSUE THREAD

**Issue by yofukami** [icat-lab/seminar_design_hakuba#5]
図書館が資料検索ガイダンスをしてくれます。
90分のパッケージ。
これを、どのタイミングで入れるかの検討が必要。

[毎回の予定](https://github.com/icat-lab/icat_lab/blob/master/basic_seminar_undergrad/autumn_basic_seminar.md)の中では、issueを建てた後にするか、codeを建てたあとにするか、、、

**Comment by Gucchiy** [comment]
@yofukami 単純に、準備次項なので、早い方が良いですよね

**Comment by yofukami** [comment]
@Gucchiy これ、第2回に入れちゃおうと思います。図書館側との相談の上で、最終確定ですが。

**Comment by yofukami** [comment]
第2回=9/22の実施で、白馬村側と調整の上、確定。
図書館に申し込み完了。

**Comment by yofukami** [comment]
学生への参加アンケートも設置。
